# Generated by Django 4.1.6 on 2024-01-01 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petapp', '0002_rename_contact_contacts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contacts',
            new_name='contacts2',
        ),
    ]
